### ISSUE TITLE
add uncaught exception handler

### ISSUE THREAD

**Issue by elijaholmos** [crimlog/hardware#4]
# Development
- [x] Catch all uncaught exceptions during runtime by implementing a handler in `app.js` 
- [x] Eat exceptions and write them to a log file, so that the program can continue to run without crashing.

# Testing
- [x] Ensure all uncaught exceptions are handled during runtime
- [x] Ensure exceptions are eaten and written to a log file so the program continually runs

**Comment by melzs0627** [comment]
Tests Passed
